#!/usr/bin/env node

var
fs = require('fs'),
path = require('path'),
args= require('pico-args'),
defaults={
	path:['.','working directory']
},
options=args.parse(defaults),
destDir = path.resolve(process.cwd(),options.path), // relative between cwd and run/update
runPath=path.dirname(process.argv[1])

fs.readlink(process.argv[1], (err, realPath)=>{
    var srcDir = err?path.resolve(runPath,'sdk'):path.resolve(path.resolve(runPath,path.dirname(realPath)),'sdk');
    (function(files, cb){
        if (!files.length) return cb()
        var
        fname = files.shift(),
        dest = path.resolve(destDir, files.shift(), fname)
        fs.createReadStream(path.resolve(srcDir,fname)).pipe(fs.createWriteStream(dest))
        arguments.callee(files, cb)
})([
        'Frame.js','js',
        'Model.js','js',
        'Module.js','js',
        'Pane.js','js',
        'Router.js','js',
        'Socket.js','js',
        'Stream.js','js',
        'network.js','js',
        'sigslot.js','js',
        'specMgr.js','js'
        ], ()=>{
        return console.log('Done')
    })
})
