#!/usr/bin/env node

var
fs = require('fs'),
path = require('path'),
destDir = path.resolve(process.cwd(),process.argv[2]||'.')

fs.readlink(process.argv[1], (err, realPath)=>{
    if (err) realPath = process.argv[1]
    var srcDir = path.dirname(realPath)+'/sdk/';
    (function(files, cb){
        if (!files.length) return cb()
        var
        fname = files.shift(),
        dest = path.resolve(destDir, files.shift(), fname)
        fs.createReadStream(srcDir+fname).pipe(fs.createWriteStream(dest))
        arguments.callee(files, cb)
    })([
        'Frame.js','js',
        'Model.js','js',
        'Module.js','js',
        'Pane.js','js',
        'Router.js','js',
        'Socket.js','js',
        'Stream.js','js',
        'network.js','js',
        'sigslot.js','js',
        'specMgr.js','js'
        ], ()=>{
        return console.log('Done')
    })
})
