Object.freeze(G_MSG = {
    TRADE: "Let's trade, here is my 'ITEM'",
    POSTFIX_SEPARATOR: " of ",
    FLEE_WIN: "You fled the battle area",
    FLEE_LOST: "You failed to flee, improve your `0613 dex and `0193 luck to increase your chances",
    BUY_LABEL: 'Get Extra Slots',
    BAG_FULL: ["You cannot receive this item. Your bag may be full."],
    TOME_FULL: ["You cannot learn this scroll. Your tome may be full."],
});

Object.freeze(G_LABEL = {
    CLOSE: 'Close',
    DONE: 'Done',
    LEAVE: 'Leave',
    OFFER: 'Donate',
    TITHE: 'Tithe', 
});

Object.freeze(G_ELEMENT_NAME = {
    0: 'None',
    1: 'Fire',
    2: 'Air',
    4: 'Water',
    8: 'Earth',
    3: 'Fire, Air',
    5: 'Fire, Water',
    7: 'Fire, Air, Water',
    9: 'Fire, Earth',
    11: 'Fire, Air, Earth',
    13: 'Fire, Water, Earth',
    6: 'Air, Water',
    10: 'Air, Earth',
    14: 'Air, Water, Earth',
    12: 'Water, Earth',
    15: 'Fire, Air, Water, Earth',
});

Object.freeze(G_STAT_NAME = [
    'Icon','Name','Desc','Level','Grade','Type','SubType',
    'HP', 'Fire', 'Dex', 'Luck', 'Str',
    'Atk', 'Atk', 'Def',
    'Plant', 'Insect', 'Beast', 'Undead', 'Demon',
    'Fire', 'Air', 'Water', 'Earth'
]);

Object.freeze(G_CREEP_TYPE_NAME = [
    'NA',
    'Plant',
    'Insect',
    'Beast',
    'Undead',
    'Demon',
]);
Object.freeze(G_HERO_CLASS_NAME = {
    1: 'Rogue',
    2: 'Monk',
    4: 'Barbarian',
    8: 'Druid',
    16: 'Hunter',
    32: 'Paladin',
    64: 'Wizard',
    128: 'Warlock',
    256: 'Ash Rat',
    512: 'Tainted Bat',
    1024: 'Dire Wolf',
    2048: 'Arctic Bear',
    17: 'Rogue, Hunter',
    34: 'Monk, Hunter',
    42: 'Monk, Druid, Paladin',
    46: 'Monk, Barbarian, Druid, Paladin',
    192: 'Wizard, Warlock',
    220: 'Barbarian, Druid, Hunter, Wizard, Warlock',
    255: 'All'
});
Object.freeze(G_OBJECT_TYPE_NAME = [
    'Empty',
    'Hero',
    'NPC',
    'Creep',
    'Chest',
    'Env',
    'Health Globe',
    'Key',
    'Potion',
    'Scroll',
    'Weapon',
    'Ammunition',
    'Armor',
    'Material',
    'Craft Ingredient',
    'Money',
    'Spell',
    'Effect',
]);
Object.freeze(G_GRADE_NAME = {
    0: 'None',
    1: 'Common',
    2: 'Charmed',
    4: 'Enchanted',
    8: 'Legendary',
    3: 'Usual',
    12: 'elite',
    6: 'Special',
    8: 'Exceptional',
    15: 'All',
});
Object.freeze(G_LEGENDARY_AFFIX = [
    ["Glimmerborg's", "Brave"],
    ["Negablade's", "Ordeal"]
]);
Object.freeze(G_ENCHANTED_PREFIX = [
'Burning','Strong','Heavy','Nimble','Crafty','Sharp','Thin','Grim','Stalwart','Bendy','Balanced','Weak','Grand','Broad','Pointy','Immovable',
'Disingenuous','Vamoose','Enamor','Bewitch','Enrapture','psychic', 'Fabled'
]);
Object.freeze(G_CHARMED_POSTFIX = [
'the Phoenix','Strength','Agility','Luck','Health','Precision','Heartseeking','Armor','Defense','Magical Attraction',
'the Heavy','the Thief','Blades','the Golem','the Ninja','the Lion','the Bounty Hunter','the Loser','the Hermit','Kings',
'Beleaguer','Ordeal','Anguish','Torment','Nightmare','Agony','Misery','Burden','Torture','Heretic','Dread','Callous','Vain','Arduous',
'Excruciate','Obliterate','Oratory','Deplorer','Unadulterated','Bewilderment','Imminent','Ruin','Despoil','Plunder','Pillage','Sack',
'Ruin','Waste','Desolation','Solitary','Deviant','Uncanny'
]);
Object.freeze(G_EQUIP_NAME = ['Helm', 'Armor', 'Weapon', 'Sheild', 'Ring', 'Ring', 'Amulet', 'Ammo']);

Object.freeze(G_OBJECT_NAME = {
    32: 'Chest',
    33: 'Empty Chest',
    34: 'Chest Key',
    35: 'Treasure Key',
    36: 'Gate Key',
    37: 'Dungeon Key',
    38: 'Mystic Key',
    39: 'Skeleton Key',
    40: 'Antidot',
    41: 'Minor Healing Potion',
    42: 'Greater Healing Potion',
    43: 'Medicinal Potion',
    44: 'Potion of Luck',
    45: 'Master Healing Potion',
    46: 'Holy Water',
    47: 'Fire Water',
    48: 'Manuscript',
    49: 'Identify Scroll',
    50: 'Teleport Scroll',
    51: 'Map',
    52: 'Tome of Knowledge',
    53: 'Tome of Wisdom',
    54: 'Tome of Divinity',
    55: 'Tome of Necromancy',
    56: 'Dagger',
    57: 'Scimitar',
    58: 'Gladius',
    59: 'Xiphos',
    60: 'Cutlass',
    61: 'Bastard Sword',
    62: 'Claymore',
    63: 'Flamebards',
    64: 'Hatchet',
    65: 'Cleaver',
    66: 'Tomahawk',
    67: 'Tabarzin',
    68: 'Double Hatchet',
    69: 'Double Axe',
    70: 'Battle Axe',
    71: 'Labrys',
    72: 'Shuriken',
    73: 'Fuuma Shuriken',
    74: 'Dart',
    75: 'Recurve Bow',
    76: 'Long Bow',
    77: 'Reflex Bow',
    78: 'Arbalest',
    79: 'ChuKoNu',
    80: 'Grenades',
    81: 'Fire Bomb',
    82: 'Thunder Crash Bomb',
    83: 'Hunter Arrows',
    84: 'Broadhead Arrows',
    85: 'Warship Arrows',
    86: 'Hunter Bolts',
    87: 'Military Bolts',
    88: 'Robe',
    89: 'Leather Armor',
    90: 'Scale Armor',
    91: 'Cuirass',
    92: 'Plate Mail',
    93: 'Light Plate',
    94: 'Field Plate',
    95: 'Full Plate',
    96: 'Hood',
    97: 'Sallet',
    98: 'Spangen Helm',
    99: 'Corinthian Helm',
    100: 'Great Helm',
    101: 'Viking Helm',
    102: 'Winged Helm',
    103: 'Barbute Helm',
    104: 'Buckler',
    105: 'Parma',
    106: 'Rondache',
    107: 'Heater',
    108: 'Kite',
    109: 'Pavise',
    110: 'Scutum',
    111: 'Heraldry',
    112: 'Orb',
    113: 'Mace',
    114: 'Wand',
    115: 'Staff',
    116: 'Aquila',
    117: 'Caduceus',
    118: 'Scepter',
    119: 'Skull Wand',
    120: 'Coins',
    121: 'Coin Stack',
    122: 'Pearls',
    123: 'Diamond',
    124: 'Ring',
    125: 'Ring',
    126: 'Amulet',
    127: 'Amulet',
    128: 'Skulls',
    129: 'Skull',
    130: 'Skeleton',
    131: 'Tomb',
    132: 'Altar of Wodinaz',
    133: 'Fountain of Eir',
    134: 'Soulstones',
    135: 'Health Globe',
    136: 'Symbol of Protection', // Pentagram
    137: 'Key of Life', // ankh
    138: 'Mark of All Seeing Eye',
    139: 'Cycle of Blood',
    140: 'Rein in the Chaos',
    141: 'The Rite of Sacrifice',
    142: 'Banner',
    143: 'Message Board',
    144: 'Rogue',
    145: 'Monk',
    146: 'Barbarian',
    147: 'Druid',
    148: 'Hunter',
    149: 'Paladin',
    150: 'Wizard',
    151: 'Warlock',
    152: 'Rat',
    153: 'Spiders',
    154: 'Salamandra',
    155: 'Spider King',
    156: 'Toad',
    157: 'Scarab',
    158: 'Centipede',
    159: 'Naga',
    160: 'Fungi',
    161: 'Hare',
    162: 'Bat',
    163: 'Bat King',
    164: 'Serpent',
    165: 'Wolf',
    166: 'Wild Boar',
    167: 'Bear',
    168: 'Slime',
    169: 'Slime King',
    170: 'Scorpion',
    171: 'Kraken',
    172: 'Vampire',
    173: 'Mummy',
    174: 'Wraith',
    175: 'Beholder',
    176: 'Goblin',
    177: 'Zombie',
    178: 'Skeleton',
    179: 'Orc',
    180: 'Cyclops',
    181: 'Werewolf',
    182: 'Golem',
    183: 'Balrog',
    184: 'Blacksmith',
    185: 'Arch-Mage',
    186: 'Town Guard',

    196: 'Whirl Wind',
    197: 'Whirl Wind',
    198: 'Whirl Wind',
    223: 'Alert',
    224: 'Twilight',
    225: 'Tremor',
    226: 'Poison Blade',
    227: 'Poison Blade',
    228: 'Poison Blade',
    253: 'Panic',
    254: 'Dread',
    255: 'Terror',
    256: 'Gaze',
    257: 'Gaze',
    258: 'Gaze',
    271: 'Burn',
    272: 'Kindle',
    273: 'Engulf',
    295: 'Fireball',
    296: 'Fireball',
    297: 'Fireball',
    301: 'Paralyze',
    302: 'Mutation',
    303: 'Venom Cloud',
    304: 'Infest',
    305: 'Outbreak',
    306: 'Plague Gas',
    328: 'Swift',
    329: 'Fury',
    330: 'Brisk',
    343: 'Consume',
    344: 'Devour',
    345: 'Voracious',
    346: 'Anger',
    347: 'Violent',
    348: 'Furious',
    349: 'Chill',
    350: 'Creepy Cold',
    351: 'Abyss Frozen',
    400: 'Drain',
    401: 'Hunger',
    402: 'Leech',
    406: 'Loot',
    407: 'Plunder',
    408: 'Pillage',
    448: 'Bone shield',
    449: 'Stone skin',
    450: 'Trauma',
    457: 'Absorb Will',
    458: 'Absorb Attack',
    459: 'Absorb Time',
    484: 'Hoard',
    485: 'Banding',
    486: 'Horde',
    496: 'Web',
    497: 'Craving',
    498: 'Crush',
    535: 'Howl',
    536: 'Shriek',
    537: 'Bad moon',
    544: 'Growth',
    545: 'Multiply',
    546: 'Conjure',
    562: 'Lycan',
    563: 'Lycan',
    564: 'Lycan',
    565: 'Nocturnal',
    566: 'Nocturnal',
    567: 'Nocturnal',
    568: 'Growl',
    569: 'Growl',
    570: 'Growl',
    571: 'Squeal',
    572: 'Squeal',
    573: 'Squeal',
    583: 'Condemn',
    584: 'Hatred',
    585: 'Vengeance',

    589: 'Burn', // reduce hp
    590: 'Curse', // reduce roll
    591: 'Plague', // reduce max hp
    592: 'Fear', // reduce atk and def 
    593: 'Chill', // cooldown stop
    594: 'Poison', // hp dun heal
    595: 'Poison Blade',
    596: 'Squeal',
    597: 'Nocturnal',
    598: 'Lycan',
    599: 'Growl',

    681: 'Stash',
    682: 'Empty stash',

    691: 'Ash Rat',
    692: 'Tainted Bat',
    693: 'Dire wolf',
    694: 'Arctic Bear',

    701: 'Prove your worth',
    702: 'Key objective',
    703: 'Creep sweeping',
    704: 'Combat training',
    705: 'Combat rewards!',
    706: 'Treasure hunting',
    707: 'Waypoint!',
    708: 'Equip items',
});
Object.freeze(G_OBJECT_DESC = {
    32: 'Contains treasures depend on your luck',
    33: 'A looted chest',
    34: 'Chest Key',
    35: 'Treasure Key',
    36: 'Use it to unlock dungeon gate to next level',
    37: 'Dungeon Key',
    38: 'Mystic Key',
    39: 'Skeleton Key',
    40: 'Drink it to cure poison',
    41: 'Drink it to restore 1 HP',
    42: 'Drink it to restore 3 HP',
    43: 'Drink it to cure for the plague',
    44: 'Drink it to be lucky for 4 turns',
    45: 'Drink it to restore 8 HP',
    46: 'Drink it to remove curse',
    47: 'Drink it to remove fear',
    48: 'Manuscript',
    49: 'Identify Scroll',
    50: 'Use it to open a town portal',
    51: 'Map',
    52: 'Tome of Knowledge',
    53: 'Tome of Wisdom',
    54: 'Tome of Divinity',
    55: 'Tome of Necromancy',
    56: 'Dagger',
    57: 'Scimitar',
    58: 'Gladius',
    59: 'Xiphos',
    60: 'Cutlass',
    61: 'Bastard Sword',
    62: 'Claymore',
    63: 'Flamebards',
    64: 'Hatchet',
    65: 'Cleaver',
    66: 'Tomahawk',
    67: 'Tabarzin',
    68: 'Double Hatchet',
    69: 'Double Axe',
    70: 'Battle Axe',
    71: 'Labrys',
    72: 'Shuriken',
    73: 'Fuuma Shuriken',
    74: 'Dart',
    75: 'Recurve Bow',
    76: 'Long Bow',
    77: 'Reflex Bow',
    78: 'Arbalest',
    79: 'ChuKoNu',
    80: 'Grenades',
    81: 'Fire Bomb',
    82: 'Thunder Crash Bomb',
    83: 'Hunter Arrows',
    84: 'Broadhead Arrows',
    85: 'Warship Arrows',
    86: 'Hunter Bolts',
    87: 'Military Bolts',
    88: 'Robe',
    89: 'Leather Armor',
    90: 'Scale Armor',
    91: 'Cuirass',
    92: 'Plate Mail',
    93: 'Light Plate',
    94: 'Field Plate',
    95: 'Full Plate',
    96: 'Hood',
    97: 'Sallet',
    98: 'Spangen Helm',
    99: 'Corinthian Helm',
    100: 'Great Helm',
    101: 'Viking Helm',
    102: 'Winged Helm',
    103: 'Barbute Helm',
    104: 'Buckler',
    105: 'Parma',
    106: 'Rondache',
    107: 'Heater',
    108: 'Kite',
    109: 'Pavise',
    110: 'Scutum',
    111: 'Heraldry',
    112: 'Orb',
    113: 'Mace',
    114: 'Wand',
    115: 'Staff',
    116: 'Aquila',
    117: 'Caduceus',
    118: 'Scepter',
    119: 'Skull Wand',
    120: 'Coins',
    121: 'Coin Stack',
    122: 'Pearls',
    123: 'Diamond',
    124: 'Ring',
    125: 'Ring',
    126: 'Amulet',
    127: 'Amulet',
    128: 'Skulls',
    129: 'Skull',
    130: 'Skeleton',
    131: 'Tomb',
    132: 'Altar of the god of creation. Make offering to god to gain piety. you may exhange piety for exhancements.',
    133: 'Drink it to restore full health',
    134: 'Soulstones',
    135: 'consume it to heal yourself (and enemies)',
    136: 'Symbol of Protection', // Pentagram
    137: 'Key of Life', // ankh
    138: 'Mark of All Seeing Eye',
    139: 'Cycle of Blood',
    140: 'Rein in the Chaos',
    141: 'The Rite of Sacrifice',
    142: 'Banner',
    143: 'Message Board',
    144: 'Rogue',
    145: 'Monk',
    146: 'Barbarian',
    147: 'Druid',
    148: 'Hunter',
    149: 'Paladin',
    150: 'An old and stinky sorcerer',
    151: 'A young and intelligent magic user, obcess with rare and forbidden tomes and bent honself to dark sorcery allow him gained powerful art of magic at young age',

    152: 'Sneaky creature, on reveal it steal a coin from crawler',
    153: 'Poisonous spider that inject poison when attacks',
    154: 'It is a creature that penetrating flames, on reveal it burns all surrounding creatures',
    155: 'When spider king reveal, all spiders gain entangle effect to trap revealer. spider kings are poisonous ',
    156: 'On reveal devour an insect to double it\s health points',
    157: 'On attack it absord one will point from defender',
    158: 'Centipede bite on reveal, causes random burn, chill or fear status effect to defender',
    159: 'Treasure protector, every looted chest increase it attack, on bury it freeze it surronding',
    160: 'When revealing fungi, it grows on all unconsume health globes',
    161: 'Born with eye open, on expose it reveal itself, on attack it attack twice',
    162: 'Deadly pest that spread plague when attack',
    163: 'All bat gain leech effect. Bat king spread plague',
    164: 'Once bite, hero can\'t escape',
    165: 'Howl when reveal, all beast gains attack points',
    166: 'On defend it gain attack point',
    167: 'On attack remove attack points, gain attack when hurt',
    168: 'A hybrid of plant and beast, it grow stronger with other plants get exposed or revealed',
    169: 'On attack it grow a slime on unconsume health globe',
    170: 'On reveal, spread poison',
    171: 'A legendary giant monster, on bury it freeze the killer, no creature can escape it\'s strong tentacles',
    172: 'A thirst vampire, on attack it leech to heal himself and grow stronger with hero blood, on bury it curse the killer',
    173: 'A cursed mummy, on bury it curse the killer',
    174: 'Angry spirit of failed heroes, on bury it curse the killer, immune to normal melee and ranged attacks',
    175: 'A hateful spherical creep, on reveal it causes fear to surrounding creatures, on attack it growth a undead on unconsume health globe',
    176: 'The rattling goblin reveals all exposed creeps, goblin steal a coin on attack',
    177: 'Slow but resilent zombie, On bury it spread plague',
    178: 'Hard and rigid skeleton, immune to normal melee and ranged attacks',
    179: 'Strong orc that on reveal it growth strong with more orc exposed or revealed, on attack it pillage 5 coins from crawler, on defend it grow stronger',
    180: 'low defense high hp, on Reveal it cause fear, on Defend it devour a random beast to heal itself',
    181: 'On expose it reveal itself, on reveal it howl to boost all beast attacks, on attack it attack twice',
    182: 'A High defense, high attack, low health stone status, it is immune to melee and ranged attack and on defend it steals cooldown time from heroes\s skills to animate itself next turn.',
    183: 'A Lord of demonic spirits, on expose it reveal itself, on attack it burn the revealer, on bury it devour a random creature to revive itself',

    184: 'Mighty dwarf that can build any item with a reasonable price',
    185: 'The leader of the mages guild, deep knowledge in making potions and enchanting items',
    186: 'Full plated town guardian, his hobby is to gamble with traveller',

    196: 'Spin attack all nearby objects',
    197: 'Spin attack all nearby objects',
    198: 'Spin attack all nearby objects',
    223: 'When reveal all expose beasts reveal itself',
    224: 'When reveal all expose undeads reveal itself',
    225: 'When reveal all expose creeps reveal itself',
    226: 'Coats weapon with poisons',
    227: 'Coats weapon with poisons',
    228: 'Coats weapon with poisons',
    253: 'When reveal you fear for 5 turns',
    254: 'When reveal you fear for 10 turns',
    255: 'When reveal you fear for 20 turns',
    256: 'Expose object at hidden cell, summon creep if failed',
    257: 'Expose object at hidden cell, summon creep if failed',
    258: 'Expose object at hidden cell, summon creep if failed',
    271: 'When reveal burn all surrounding creatures for 5 turns',
    272: 'When reveal hero burn for 7 turns',
    273: 'When reveal burn hero for 12 turns',
    295: 'Hurls a fiery ball to selected cell',
    296: 'Hurls a fiery fireball to selected cell',
    297: 'Hurls a fiery mateor to selected cell',
    301: 'Whenever deal damage to hero, venom is injected to hero',
    302: 'When reveal, all spiders gain paralyze',
    303: 'When die, scorpion emits venom gas and poison to all surronding creature',
    304: 'Whenever deal damage to hero, plague is infested to hero',
    305: 'When reveal, all bats gain infest',
    306: 'When die, zombie emits plague cloud and infest all surronding creature',
    328: 'Whenever attack, hare deal double the damage',
    329: 'When attack, werewolf attacks three times',
    330: 'When attack, kraken attacks four times',
    343: 'When reveal toad devour an insect randomly to increase it\'s health points',
    344: 'Whenever dealt damage by hero, cyclop devour a random beast to heal itself',
    345: 'When dead, Balrog devour a random demon to revive itself',
    346: 'Whenever dealt damage by hero, damaged creep gain one attack point',
    347: 'Whenever dealt damage by hero, damaged creep gain two attack points',
    348: 'Whenever dealt damage by hero, damaged creep gain five attack points',
    349: 'When killed, it chills the surrounding for 5 turns',
    350: 'When reveal, it spine chill the hero for 10 turns',
    351: 'When killed, it deep frost the hero for 20 turns',
    400: 'Whenever deals damage to hero, bat gain one health point',
    401: 'When reveal, all bats gain drain ability. Whenever deals damage to hero, gain one health',
    402: 'Whenever deals damage to hero, vampire gain one health point and three attack points',
    406: 'When reveal loot one coin from hero',
    407: 'Whenever deals damage to hero, goblin plunder one coin from hero',
    408: 'Whenever deals damage to hero, orc pillage five coins from hero',
    448: 'Immune to ranged attacks',
    449: 'Immune to melee attacks',
    450: 'Immune to both normal ranged and melee attack',
    457: 'Whenever deals damage the hero, hero loses one will point as well',
    458: 'Whenever deals damage the hero, hero loses one attack point as well',
    459: 'Whenever dealt damage by hero, golem absorb cooldown time from hero to reanimate itself',
    484: 'When reveal, number of looted chests add to it attack power',
    485: 'When reveal, number of revealed or exposed plants add to it\'s defense points',
    486: 'When reveal, number of revealed or exposed orcs and goblins add to it\'s defense points',
    496: 'Whenever deals damage to hero, hero can\'t flee for 1 turns',
    497: 'Whenever deals damage to hero, hero can\t flee for 2 turns',
    498: 'When reveal, hero is trapped and can\'t flee for 10 turns',
    535: 'When reveal, all wolf gain attack point',
    536: 'When reveal, it awake all exposed creeps, and make them reveal',
    537: 'When reveal, all beast gain attack points',
    544: 'When reveal, fungi growth on all unconsume health globes',
    545: 'When reveal, slime growth on all unconsume health globes',
    546: 'When killed, it conjure undead all unconsume health globes',
    562: 'Shape shifting to a fast and furious dire wolf that can spread poison when attack for 5 turns',
    563: 'Shape shifting to a fast and furious dire wolf that can spread poison when attack for 10 turns',
    564: 'Shape shifting to a fast and furious dire wolf that can spread poison when attack for 20 turns',
    565: 'Shape shifting to a tainted bat that spread plague to any object come in contact for 5 turns',
    566: 'Shape shifting to a tainted bat that spread plague to any object come in contact for 10 turns',
    567: 'Shape shifting to a tainted bat that spread plague to any object come in contact for 20 turns',
    568: 'Shape shifting to a mighty arctic bear that chilled attack creeps for 5 turns',
    569: 'Shape shifting to a mighty arctic bear that chilled attack creeps for 10 turns',
    570: 'Shape shifting to a mighty arctic bear that chilled attack creeps for 20 turns',
    571: 'Shape shifting to ash rat that burn any object come in contact for 5 turns',
    572: 'Shape shifting to ash rat that burn any object come in contact for 10 turns',
    573: 'Shape shifting to ash rat that burn any object come in contact for 20 turns',
    583: 'When killed, it curses the hero for 5 turns',
    584: 'When killed, it curses the hero for 10 turns',
    585: 'When killed, it curses the hero for 20 turns',

    589: 'Reduce HP per turn', // burned 
    590: 'Increase skill casting cost', // cursed 
    591: 'Half attack and defense points', // plagued 
    592: 'Prevent creep\'s casting skills or stop hero will point regeneration', // feared 
    593: 'Immobilize creeps or stop hero skill cooldown', // chilled 
    594: 'Prevent creature from healing', // poisoned 
    595: 'Poison creature when deal damage',
    596: 'Weak creature that burn creep when touch',
    597: 'Weak creature that spread plague to contacted creep',
    598: 'Fast and furious creature that spread poison when attack',
    599: 'Sturdy and strong creature that freeze contact',

    681: 'It holds items for your friends',
    682: 'It holds items for your friends',

    701: "Welcome to Loki's Trial, God has created this town to guard the dungeon named Loki's Trail, to test the strength and purity of our soul. travel down to the deepest level and retrieve a soul stone to complete the test",
    702: "Find a key `036 to move on to next level by unlocking the exit `012",
    703: 'The key to down stair is concealed in dungeon, tab on hidden cell `08 to reveal it, but hidden cell may contains dangerous creep, the digit on cell indicates the number of adjacent cells which contains creeps. You can use this information to deduce creep-free cell, reveal creep-free cells to discover the key. Warning! a revealed creep may attack you immediately. if you get killed your soul will join Valhala and God Wodinaz will reincarnate you, so don\'t be afraid to try',
    704: 'The key to next level is keep by one of the hidden creeps, to get the key creeps must be defeated. Use the digit on the floor to deduce the creep location and use skill from tome to expose creep. exposed creeps has a `0202 icon on them and they don\'t attack you by exposing them. to attack creep, tab on creep and choose fight.',
    705: 'Beside getting key, defeating creep also reward you a health globe `0135 and a piety point `0196 . consume a health globe restore one hit point 663 for you and all exposed creeps. Piety point can be used to get rewards from God Wodinaz Altar at town',
    706: 'Creeps are not the only objects conceled in dungeon, there treasure chests that you can find to get equipments, consumable items and spell scrolls. Expose all concealed objects to find treasures',
    707: 'There is a waypoint in this dungeon. A Waypoint is a way to fast travel between dungeon and town. They appear as `09 when inactive, and `017 when activated. besides waypoint there are teleport scrolls to travel back to town immediately',
    708: 'Looted artifacts from treasure chest are kept in your bag. to equip item from bag, tab on the item and choose Equip. You can see equip item from expanded player stats window. Item may have enchantment that contain elemental power. Your skill requires elemental power to level up',
});
Object.freeze(G_MEDAL_GRADE = ['Medal of ', 'Medal of ', 'Order of ', 'Hero of ', 'Hero of ']);
Object.freeze(G_MEDAL_NAME = {
won:            'Glory',
die:           'the Steadfast', 
gold:           'Wealth',
piety:          'Faith',
chest:          'Quest',
fame:           'Fame',
common:         'Favour',
charm:          'Luck',
enchant:        'Fortune',
legendary:      'Fate',
drink:          'Indulgence',
learn:          'Arcanum', 
plant:          'Blight',
insect:         'Pestilence',
beast:          'Fury',
undead:         'Acolyte',
demon:          'Torment',
def:            'Fortitude',
patk:           'Mastery',
ratk:           'Deadeye',
will:           'Oath',
cast:           'Adept',
burn:           'Inferno',
curse:          'Conjure',
plague:         'Retribution',
fear:           'Terror',
frozen:         'Blizzard',
poison:         'Alchemy',
});
Object.freeze(G_MEDAL_DESC = {
won:            'The deeper the dungeon, the more glory in overcoming it and retrieve the soul stones',
die:           'A dutifully fearless spirit that stuborn challenge the legion from Hel, rise every time falling', 
gold:           'Earning golds',
piety:          'Earning piety points',
chest:          'Open chests on dungeon floors',
fame:           'Actively trading with friends',
common:         'Found common items',
charm:          'Found charmed items',
enchant:        'Found enchanted items',
legendary:      'Found legendary items',
drink:          'Drink potions to maintain healthy state 324349 98958924 445329 23424',
learn:          'Learning arcane skills from scrolls', 
plant:          'Kill plant type creeps',
insect:         'kil insect type creeps',
beast:          'kill beast type creeps',
undead:         'kill undead type creeps',
demon:          'kill demon type creeps',
def:            'Block incoming attack',
patk:           'Deal melee damage',
ratk:           'Deal range damage',
will:           'Deal damage with skills',
cast:           'Actively cast spell',
burn:           'Burn creeps number of times',
curse:          'Curse creeps number of times',
plague:         'Spread disease to creeps',
fear:           'Causing fear to creeps',
frozen:         'Freeze creeps number of times',
poison:         'Spread poison to creeps',
});
